<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Bodak\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getOrderCustomFields();
?>
<?php if($customFields): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="order-information">
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Buyer') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutBuyerName()); ?>
                    </div>
                </div>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Buyer email address') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutBuyerEmail()); ?>
                    </div>
                </div>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Purchase order no.') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutPurchaseOrderNo()); ?>
                    </div>
                </div>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Goods mark') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getCheckoutGoodsMark()); ?>
                    </div>
                </div>
            </div>

            <div class="order-information">
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Comment') ?></span></strong>
                    <div class="box-content">
                        <?php echo nl2br($this->escapeHtml($customFields->getCheckoutComment())); ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
